-- 12.Find the total revenue generated by each employee:

/*
The query combines data from the "employees," "orders," and "order_details" tables. It calculates the total revenue generated by each employee based on the products they sold. 
The query groups the results by employee ID, first name, and last name to provide a summary of total revenue for each employee.
*/


SELECT employees.employee_id, CONCAT(employees.first_name, ' ', employees.last_name) AS employee_name, SUM(order_details.quantity * products.unit_price) AS total_revenue
FROM employees
INNER JOIN orders ON employees.employee_id = orders.employee_id
INNER JOIN order_details ON orders.order_id = order_details.order_id
INNER JOIN products ON order_details.product_id = products.product_id
GROUP BY employees.employee_id;
